imports:
    - { resource: parameters.yml }
    - { resource: ns_admin.bundles.yml }
    - { resource: @NSCoreBundle/Resources/config/core-config.yml }

framework:
    templating:
        assets_version: '1'

# Avalanche Imagine
avalanche_imagine:
    source_root:  %kernel.root_dir%/../web
    web_root:     %kernel.root_dir%/../web
    filters:
        ns_admin_image:
            type:    thumbnail
            options: { size: [200, 200], mode: inset }
        ns_admin_preview:
            type:    thumbnail
            options: { size: [128, 128], mode: outbound }

        clients_small:
            type: thumbnail
            options: { size: [67, 67], mode: inset }

# FK ElFinder Bundle config
fm_elfinder:
    editor: ckeditor
    connector:
        roots:
            music:
                driver: LocalFileSystem
                path: 'upload/music'
                upload_allow:
                    - 'image/png'
                    - 'image/jpg'
                    - 'image/jpeg'
                    - 'image/gif'
                    - 'audio/mpeg'
                upload_deny: ['all']
                upload_max_size: 100M
