templates:
    -
        path:    "NSCmsBundle:Pages:page.html.twig"
        title:   "Default page template"
        default: true
        areas:
            -
                name: header
                title: "Верхняя панель"
                fixed: true
            -
                name: content_fixed
                title: "Верхняя часть контентной области"
                fixed: true
            -
                name: content_header
                title: "Заголовок контентной области"
            -
                name: content
                title: "Контентная область"
            -
                name: footer
                title: "Нижняя часть"
                fixed: true
